### PR TITLE
Fix toggle buttons in preferences

### LINKED ISSUE #2058: [$80] Profile Page: Email preferences are not reflecting in real time
**Describe the bug**
Email preferences are not reflecting in real time. Field statuses are reflecting only after refreshing the page

**To Reproduce**
1. Go to  Email preferences page('https://www.topcoder-dev.com/settings/preferences')
2. Enable any preference ex: 'Design Newsletter'
3. Check the Status message at the top(should say "Changes are saved")
4. Verify the preference option status(step2)

**Expected behavior**
Preference status should be reflected in real time.

**Screenshots**
https://dl.dropboxusercontent.com/s/b2x908ztaid0h79/oTkC3EZaly.mp4

**Desktop (please complete the following information):**
 Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Fixes #2058

### CODE REVIEW

File: src/shared/components/Settings/Preferences/Email/index.jsx [hunk 1]
```diff
@@ -93,11 +93,20 @@ export default class EmailPreferences extends ConsentComponent {
...
+    }
+    return false;
+  }
+
   onHandleChange(id, checked) {
     this.showConsent(this.onChange.bind(this, id, checked));
   }
 
   onChange(id, checked) {
+    document.querySelectorAll(`#pre-onoffswitch-${id}`).forEach((el) => { el.checked = checked; }); // eslint-disable-line no-param-reassign
```
Comment (Gauravseta) [inline src/shared/components/Settings/Preferences/Email/index.jsx]: @ThomasKranitsas this line was required, needed to mark it check/uncheck explicitly. good one

Comment (r0hit-gupta) [reply src/shared/components/Settings/Preferences/Email/index.jsx]: Well, we always need to find workarounds as a developer. 😉
