### PR TITLE
fixed #366 passing domain for user profiles avatar

### LINKED ISSUE #366: [$10] - Tapping on the user profile image won't go to the profile page
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges?

- Go to 'Past Challenges' and click on the profile image

Actual Result(s)
-----------------------------------------------------------------
- Tapping on the user profile image won't go to the profile page. Instead it will show 'undefined' message

Expected Result(s)
-----------------------------------------------------------------
- When tap on a profile image must open the profile page of the user

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #366 passing domain for user profiles avatar

### CODE REVIEW

File: src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx [hunk 1]
```diff
@@ -374,7 +374,7 @@ class ChallengeStatus extends Component {
       return (
         <div styleName="avatar-container" key={winner.handle}>
           <UserAvatarTooltip user={userProfile}>
-            <LeaderboardAvatar member={winner} />
+            <LeaderboardAvatar member={winner} domain={config.URL.BASE} />
```
Comment (birdofpreyru) [inline src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx]: @shubhendusaurabh Here, and in the other file, do we really need to pass in the domain via the props? I believe, as now we get it from config, we can just remove such prop and related typechecks, etc. Please correct the code (or correct me, if there are some use cases that still need custom domains.)

**Comment by shubhendusaurabh** [comment]
@birdofpreyru updated
