### PR TITLE
fixed #258 removed redundant part from url

### LINKED ISSUE #258: [$10] - Profile URL have extra part '/design' in 'Submission' tab
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Click on the 'Submission' tab

- Click 'chamdi' from the submissions

Actual Result(s)
-----------------------------------------------------------------
- Profile URL have extra part '/design' in 'Submission' tab
- https://www.topcoder.com/member-profile/chamdi/design

Expected Result(s)
-----------------------------------------------------------------
- Must remove the '/design' part from the URL or must navigate to the design portfolio of the users instead profile page
- https://www.topcoder.com/member-profile/chamdi

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #258 removed redundant part from url

### CODE REVIEW

File: src/shared/components/challenge-detail/Submissions/index.jsx [hunk 1]
```diff
@@ -19,7 +19,7 @@ function renderSubmission(s) {
       <div styleName="bottom-info">
         <div styleName="links">
           <a target="_blank" href={`${config.URL.STUDIO}?module=DownloadSubmission&sbmid=${s.submissionId}`}>{`#${s.submissionId}`}</a>
-          <a styleName="handle" target="_blank" href={`${config.URL.BASE}/member-profile/${s.submitter}/design`}>{s.submitter}</a>
+          <a styleName="handle" target="_blank" href={`${config.URL.BASE}/member-profile/${s.submitter}`}>{s.submitter}</a>
```
Comment (birdofpreyru) [inline src/shared/components/challenge-detail/Submissions/index.jsx]: I believe, should be `${config.URL.BASE}/members/${s.submitter}`, as it is where we got redirected anyway, if do the actions from the issue description. So, we can just go directly there. Please update

**Comment by shubhendusaurabh** [comment]
@birdofpreyru updated
