### PR TITLE
fixed #349 challenge over text in my-submissions

### LINKED ISSUE #349: [$10] - time displays for past challenge
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user 

- Go to http://community-app.topcoder.com/challenges/30058497/my-submissions 

- observe 

Actual Result(s)
-----------------------------------------------------------------
-  time displays for past challenge 

Expected Result(s)
-----------------------------------------------------------------
- Should show like challenge is end 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1
- **Browser(s):** FF 55.0.3

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
screenshot-0bcc0aa7-5704-4b74-b7d4-49b5953caceb-2017-08-27-20-57-34

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #349 challenge over text in my-submissions

### CODE REVIEW

File: src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx [hunk 1]
```diff
@@ -72,10 +72,17 @@ export default function SubmissionManagement(props) {
         </div>
         <div styleName="right-col">
           <p styleName="round">{currentPhase.phaseType}</p>
-          <p styleName="time-left">
-            {days > 0 && (`${days}D`)} {hours}H {minutes}M
-          </p>
-          <p styleName="left-label">left</p>
+          {challenge.status !== 'COMPLETED' &&
```
Comment (birdofpreyru) [inline src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx]: For cleaner code, please combine these two conditional blocks into one like:
```
{
  challenge.status === 'COMPLETED' ? (
    /* Markup for this case */
  ) : (
    /* Render markup for this case */
  )
}
```
Otherwise the code looks correct

Comment (shubhendusaurabh) [reply src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx]: @birdofpreyru updated
