### PR TITLE
issue 4982 fix

### LINKED ISSUE #4982: [$40] Add more Sort Options
We have only the sort by `most recent` and `Title A-Z`. Are we going to add the rest.

My Challenges:

- Time to submit
- number of registrants
- number of submissions
- Prize high to low

Open for Registration:

- Time to Register
- Time to Submit
- number of registrants
- number of submissions
- Prize high to low

Ongoing Challenges:

- Current Phase
- Prize high to low

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**
#4982

### CODE REVIEW

**Review by luizrrodrigues — CHANGES_REQUESTED** [review]
image

**Review by luizrrodrigues — APPROVED** [review]

File: src/shared/utils/challenge-listing/sort.js [hunk 1]
```diff
@@ -42,43 +42,46 @@ export default {
...
-  // [SORTS.PRIZE_HIGH_TO_LOW]: {
-  //   func: (a, b) => b.totalPrize - a.totalPrize,
-  //   name: 'Prize high to low',
-  // },
-  // [SORTS.TIME_TO_REGISTER]: {
-  //   func: (a, b) => {
-  //     const aDate = moment(a.registrationEndDate || a.submissionEndTimestamp);
-  //     const bDate = moment(b.registrationEndDate || b.submissionEndTimestamp);
+  [SORTS.PRIZE_HIGH_TO_LOW]: {
+    func: (a, b) => b.totalPrize - a.totalPrize,
```
Comment (luizrrodrigues) [inline src/shared/utils/challenge-listing/sort.js:46]: @PrakashDurlabhji Please comment unnecessary function

File: src/shared/utils/challenge-listing/sort.js [hunk 2]
```diff
@@ -42,43 +42,46 @@ export default {
...
+    name: 'Prize high to low',
+    order: 'desc',
+  },
+  [SORTS.TIME_TO_REGISTER]: {
+    func: (a, b) => {
```
Comment (luizrrodrigues) [inline src/shared/utils/challenge-listing/sort.js:51]: @PrakashDurlabhji Please comment unnecessary function

File: src/shared/utils/challenge-listing/sort.js [hunk 3]
```diff
@@ -42,43 +42,46 @@ export default {
...
-  //       }
-  //       return moment(o.submissionEndTimestamp);
-  //     }
+      return aDate.diff(bDate);
+    },
+    name: 'Time to register',
+    order: 'desc',
+  },
+  [SORTS.TIME_TO_SUBMIT]: {
+    func: (a, b) => {
```
Comment (luizrrodrigues) [inline src/shared/utils/challenge-listing/sort.js:65]: @PrakashDurlabhji Please comment unnecessary function

File: src/shared/utils/challenge-listing/sort.js [hunk 4]
```diff
@@ -6,25 +6,25 @@ import moment from 'moment';
...
   REVIEW_OPPORTUNITIES_START_DATE: 'review-opportunities-start-date',
 };
 
 export default {
-  // [SORTS.CURRENT_PHASE]: {
-  //   func: (a, b) => a.status.localeCompare(b.status),
-  //   name: 'Current phase',
-  // },
+  [SORTS.CURRENT_PHASE]: {
+    func: (a, b) => a.status.localeCompare(b.status),
```
Comment (luizrrodrigues) [inline src/shared/utils/challenge-listing/sort.js:25]: @PrakashDurlabhji Please comment unnecessary function

**Review by luizrrodrigues — CHANGES_REQUESTED** [review]

File: src/shared/utils/challenge-listing/sort.js [hunk 5]
```diff
@@ -6,25 +6,25 @@ import moment from 'moment';
...
-  // CURRENT_PHASE: 'current-phase',
+  CURRENT_PHASE: 'current-phase',
   MOST_RECENT: 'updated',
   MOST_RECENT_START_DATE: 'startDate',
   // NUM_REGISTRANTS: 'num-registrants',
   // NUM_SUBMISSIONS: 'num-submissions',
-  // PRIZE_HIGH_TO_LOW: 'prize-high-to-low',
-  // TIME_TO_REGISTER: 'time-to-register',
-  // TIME_TO_SUBMIT: 'time-to-submit',
+  PRIZE_HIGH_TO_LOW: 'prizeSets.prizes.value',
```
Comment (luizrrodrigues) [inline src/shared/utils/challenge-listing/sort.js:14]: @PrakashDurlabhji Please change `prizeSets.prizes.value` to `overview.totalPrizes`

**Review by luizrrodrigues — CHANGES_REQUESTED** [review]
