### PR TITLE
fixed #257 corrected download link for design submission download

### LINKED ISSUE #257: [$40] - Can't download the submissions from 'Winners' tab instead code displayed
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Click on the 'Winners' tab

- Click Download from 'johan_92'

Actual Result(s)
-----------------------------------------------------------------
- Can't download the submissions from 'Winners' tab instead code displayed

Expected Result(s)
-----------------------------------------------------------------
- Must able to download the submissions; if not must display a validation message

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
{
  "error": {
    "name": "Unauthorized",
    "value": 401,
    "description": "Authentication credentials were missing or incorrect.",
    "details": "Authentication details missing or incorrect."
  },
  "serverInformation": {
    "serverName": "TopCoder API",
    "apiVersion": "0.0.1",
    "requestDuration": 4,
    "currentTime": 1503627989177
  },
  "requesterInformation": {
    "id": "5602cfacfa335587c7c709df698a47c5c3cd62e6-UAoaXpOHTwfCnR1e",
    "remoteIP": "123.231.111.23",
    "receivedParams": {
      "submissionType": "original",
      "apiVersion": "v2",
      "submissionId": "238671",
      "action": "downloadDesignSubmission"
    }
  }
}

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #257 corrected download link for design submission download

### CODE REVIEW

File: src/shared/components/challenge-detail/Winners/index.jsx [hunk 1]
```diff
@@ -78,7 +78,8 @@ export default function Winners(props) {
                   <a
                     styleName="download"
                     target="_blank"
-                    href={w.submissionDownloadLink}
+                    href={`${config.URL.STUDIO}/` +
+                          `?module=DownloadSubmission&sbmid=${submissionId}`}
```
Comment (birdofpreyru) [inline src/shared/components/challenge-detail/Winners/index.jsx]: @shubhendusaurabh The new links seems to work fine for design challenges, but does not work for development ones. I guess, you should update it to use original link for dev challenges, and the last one for design. Also, you should not use `+` to concatentate strings (it actually should cause a ESLint error).

**Comment by shubhendusaurabh** [comment]
@birdofpreyru updated
